#!/bin/bash

# Non-official images are built from https://github.com/ruippeixotog/quicksort-docker
source "$1"/.env

if [[ -z $DOCKER_IMAGE ]]; then
  echo "Error: no Docker image for $1 was defined."
  exit 1
fi

docker_run() {
  docker run --rm --entrypoint= -v "$PWD":/quicksort $DOCKER_ARGS $@
}

if [[ $2 == shell ]]; then
  docker_run -it -w /quicksort/"$1" $DOCKER_IMAGE bash
else
  docker_run -w /quicksort $DOCKER_IMAGE bash ./test "$1"
fi
