#!/bin/bash

# Non-official images are built from https://github.com/ruippeixotog/quicksort-docker
source "$1"/.env

if [[ -z $DOCKER_IMAGE ]]; then
  echo "Error: no Docker image for $1 was defined."
  exit 1
fi

docker run --rm -v "$PWD":/quicksort -w /quicksort $DOCKER_ARGS $DOCKER_IMAGE bash ./test "$1"
